import { NotesForm } from "./components/NotesForm";

export default function App() {
  return (
    <>
      <header>
        <h1>StudyBuddy</h1>
        <p>Paste your notes. Get flashcards back, generated by Claude.</p>
      </header>
      <main>
        <NotesForm />
      </main>
      <footer>
        <p>
          Built as a capstone project. AI integration: Claude API (via a
          Netlify serverless function).
        </p>
      </footer>
    </>
  );
}
